Update GlobalRuntimeImpl.java
`host` variable has form _IP:port_, so the (ignored) exception occurs:
```
java.net.UnknownHostException: 192.168.0.100:5701: invalid IPv6 address
        at java.net.InetAddress.getAllByName(InetAddress.java:1170)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at java.net.InetAddress.getByName(InetAddress.java:1077)
        at apgas.impl.GlobalRuntimeImpl.<init>(GlobalRuntimeImpl.java:289)
        at apgas.GlobalRuntime$GlobalRuntimeWrapper.<clinit>(GlobalRuntime.java:41)
        at apgas.GlobalRuntime.getRuntimeImpl(GlobalRuntime.java:65)
        at apgas.GlobalRuntime.getRuntime(GlobalRuntime.java:56)
        at apgas.GlobalRuntime.main(GlobalRuntime.java:98)
```
Removing port part from the host name fixes the issue.